# Generated by Django 4.2 on 2025-05-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Имя:')),
                ('Year', models.IntegerField(default=2000)),
                ('description', models.TextField()),
                ('poster', models.ImageField(upload_to='images/')),
                ('trailer', models.URLField()),
                ('movie', models.FileField(upload_to='movies/')),
                ('country', models.CharField(max_length=250)),
                ('categories', models.ManyToManyField(to='movie.category')),
            ],
        ),
    ]
